MySQL:
  SSL: false
  Host: "127.0.0.1"
  Port: "3306"
  Database: "database"
  User: "root"
  Password: ""

TeamSize: 4
CoinsAfterWin: 25
CreditsAfterWin: 0.5
CoinsAfterKill: 5
CreditsAfterKill: 0.15
CoinsFairPlay: 15