author: pauhull
name: PaintWars
version: 1.0
main: de.pauhull.paintwars.PaintWars
depend: [TimoCloud]
softdepend: [Multiverse-Core, NickAPI, Friends, NpcApi]

commands:
  setlocation:
  start:
  stats: