author: pauhull
name: PaintWars
version: 1.0
main: de.pauhull.paintwars.PaintWars
depend: [TimoCloud]
softdepend: [iDisguise, Multiverse-Core, NickAPI, Friends]

commands:
  setlocation:
  start:
  stats: